apiVersion: batch/v1
kind: Job
metadata:
  name: manetu-sparql-loadtest
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: sparql-loadtest
        image: manetuops/sparql-loadtest:latest
        imagePullPolicy: Always
        env:
          - name: MANETU_URL
            value: https://ingress.manetu-platform
          - name: LOG_LEVEL
            value: info
          - name: LOADTEST_CONCURRENCY
            value: "64"
          - name: LOADTEST_NR
            value: "10000"
          - name: LOADTEST_QUERY
            value: "/etc/manetu/loadtest/query.sparql"
          - name: LOADTEST_BINDINGS
            value: "/etc/manetu/loadtest/bindings.csv"
        envFrom:
          - secretRef:
              name: manetu-sparql-loadtest
        volumeMounts:
          - name: data
            mountPath: "/etc/manetu/loadtest"
            readOnly: true
      volumes:
      - name: data
        configMap:
          name: manetu-sparql-loadtest
