apiVersion: batch/v1
kind: Job
metadata:
  name: manetu-sparql-loadtest
spec:
  template:
    spec:
      containers:
      - name: sparql-loadtest
        image: manetuops/sparql-loadtest:0.0.1
        imagePullPolicy: Always
        env:
          - name: MANETU_URL
            value: https://ingress.manetu-platform
          - name: LOG_LEVEL
            value: info
          - name: LOADTEST_CONCURRENCY
            value: "64"
          - name: LOADTEST_NR
            value: "10000"
          - name: LOADTEST_QUERY
            value: "/etc/manetu/loadtest/examples/label-by-email.sparql"
          - name: LOADTEST_BINDINGS
            value: "/etc/manetu/loadtest/examples/bindings.csv"
        envFrom:
          - secretRef:
              name: manetu-sparql-loadtest
      restartPolicy: Never
